export const actionTypes = {
  FETCH_BAGS_COMPLETED: "FETCH_BAGS_COMPLETED",
  UPDATE_MEMBER_FIELD: "UPDATE_MEMBER_FIELD",
  SAVE_BAG: "SAVE_BAG",
  FETCH_ITEMS_COMPLETED: "FETCH_ITEMS_COMPLETED",
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE"
};
